// AUTO-GENERATED from FileRaw/DES-01-04-2026.pdf
// Do NOT edit by hand — rigenerare con tools/import-fatture-anagrafica.py
//
// Anagrafica completa dei Cedente/prestatore estratta dalle fatture passive
// PDF (AssoSoftware/FatturaPA). Chiave di deduplicazione = P.IVA (o codice
// fiscale / nome se P.IVA manca). Fatture analizzate: 278.
// Fornitori unici trovati: 57.
// IBAN scartati per conflitto (più valori per lo stesso cedente):
//   - LABORATORIO ODONTOTECNICO M.B. SRL: IT02E0538751061000049436295 x1, IT04N0569651060000002776X26 x3
//   - MARCI' RACHELE: IT59Y0358901600010570958298 x5, IT51O0538711111000042566669 x1

namespace Chipdent.Web.Infrastructure.Mongo;

internal static class FattureFornitoriAnagraficaData
{
    public sealed record Riga(
        string RagioneSociale,
        bool IsPersonaFisica,
        string? PartitaIva,
        string? CodiceFiscale,
        string? Indirizzo,
        string? CodicePostale,
        string? Localita,
        string? Provincia,
        string? Paese,
        string? Telefono,
        string? Email,
        string? Pec,
        string? Iban);

    public static IReadOnlyList<Riga> Righe { get; } = new Riga[]
    {
        new(
            RagioneSociale: "2BL MEDICA SRL",
            IsPersonaFisica: false,
            PartitaIva: "03401220128",
            CodiceFiscale: "03401220128",
            Indirizzo: "Via A. da Brescia 4",
            CodicePostale: "21013",
            Localita: "Gallarate",
            Provincia: "VA",
            Paese: "IT",
            Telefono: null,
            Email: null,
            Pec: null,
            Iban: null),
        new(
            RagioneSociale: "Air Liquide Italia Gas e Servizi Srl",
            IsPersonaFisica: false,
            PartitaIva: "12874240158",
            CodiceFiscale: "12874240158",
            Indirizzo: "Via Bisceglie 66",
            CodicePostale: "20152",
            Localita: "Milano",
            Provincia: "MI",
            Paese: "IT",
            Telefono: "800-442443",
            Email: "cesals.sanita@airliquide.com",
            Pec: null,
            Iban: "IT29X0100501604000000000153"),
        new(
            RagioneSociale: "ARUBA SPA",
            IsPersonaFisica: false,
            PartitaIva: "01573850516",
            CodiceFiscale: "04552920482",
            Indirizzo: "VIA SAN CLEMENTE 53",
            CodicePostale: "24036",
            Localita: "PONTE SAN PIETRO",
            Provincia: "BG",
            Paese: "IT",
            Telefono: null,
            Email: null,
            Pec: null,
            Iban: null),
        new(
            RagioneSociale: "BATTISTINI CHIARA",
            IsPersonaFisica: true,
            PartitaIva: "01254820119",
            CodiceFiscale: "BTTCHR78H46I449Q",
            Indirizzo: "VIA SIMONE D'ORSENIGO 3",
            CodicePostale: "20135",
            Localita: "Milano",
            Provincia: "MI",
            Paese: "IT",
            Telefono: "3479140115",
            Email: "chiabat.mi@gmail.com",
            Pec: null,
            Iban: null),
        new(
            RagioneSociale: "BERETTA GIANCARLO & C. SNC",
            IsPersonaFisica: false,
            PartitaIva: "00685590960",
            CodiceFiscale: "00680380151",
            Indirizzo: "VIA EDOARDO FERRAVILLA, 45",
            CodicePostale: "20832",
            Localita: "DESIO",
            Provincia: "MB",
            Paese: "IT",
            Telefono: null,
            Email: null,
            Pec: null,
            Iban: "IT81W0344033100000000767000"),
        new(
            RagioneSociale: "BIOLOGITECH SRL",
            IsPersonaFisica: false,
            PartitaIva: "07080590966",
            CodiceFiscale: "07080590966",
            Indirizzo: "Via Giuseppe Di Vittorio, 30",
            CodicePostale: "20068",
            Localita: "PESCHIERA BORROMEO",
            Provincia: "MI",
            Paese: "IT",
            Telefono: "02 55300456",
            Email: "info@biologitech.it",
            Pec: null,
            Iban: null),
        new(
            RagioneSociale: "BONFANTI ELISA",
            IsPersonaFisica: true,
            PartitaIva: "10625760961",
            CodiceFiscale: "BNFLSE92M66D286Q",
            Indirizzo: "VIA DON GUANELLA 9/D",
            CodicePostale: "22072",
            Localita: "CERMENATE",
            Provincia: "CO",
            Paese: "IT",
            Telefono: null,
            Email: null,
            Pec: null,
            Iban: null),
        new(
            RagioneSociale: "BORZI' VALERIA GIULIA",
            IsPersonaFisica: false,
            PartitaIva: "06246190877",
            CodiceFiscale: "BRZVRG98C56G371T",
            Indirizzo: "VICO GIULIO NATTA 32",
            CodicePostale: "95047",
            Localita: "Paterno'",
            Provincia: "CT",
            Paese: "IT",
            Telefono: null,
            Email: null,
            Pec: null,
            Iban: "IT71U0200809500000421130401"),
        new(
            RagioneSociale: "CAZZANIGA UBERTO MARIA PIERUGO",
            IsPersonaFisica: true,
            PartitaIva: "04967540966",
            CodiceFiscale: "CZZBTM80P04B729W",
            Indirizzo: "VIA SANT'ANTONIO 2",
            CodicePostale: "20853",
            Localita: "Biassono",
            Provincia: "MB",
            Paese: "IT",
            Telefono: null,
            Email: null,
            Pec: null,
            Iban: "IT25V0306932540000005856168"),
        new(
            RagioneSociale: "COLLEONI FABIO PIETRO",
            IsPersonaFisica: true,
            PartitaIva: "10362950155",
            CodiceFiscale: "CLLFPT62R24F205C",
            Indirizzo: "VIA ANTONIO CANOVA 1",
            CodicePostale: "20145",
            Localita: "MILANO",
            Provincia: "MI",
            Paese: "IT",
            Telefono: null,
            Email: null,
            Pec: null,
            Iban: "IT48M0329601601000067680773"),
        new(
            RagioneSociale: "COMPASS BANCA SPA",
            IsPersonaFisica: false,
            PartitaIva: "10536040966",
            CodiceFiscale: "00864530159",
            Indirizzo: "VIA CALDERA 21",
            CodicePostale: "20153",
            Localita: "MILANO",
            Provincia: "MI",
            Paese: "IT",
            Telefono: "02 721321",
            Email: "compass@pec.compassonline.it",
            Pec: null,
            Iban: null),
        new(
            RagioneSociale: "CONFIDENT COMMERCIALE HOLDING S.P.A.",
            IsPersonaFisica: false,
            PartitaIva: "04099280127",
            CodiceFiscale: "11659240961",
            Indirizzo: "Via GIACOMO MATTEOTTI 2",
            CodicePostale: "21013",
            Localita: "GALLARATE",
            Provincia: "VA",
            Paese: "IT",
            Telefono: "03311531396",
            Email: "cchsrl@pec.cgn.it",
            Pec: null,
            Iban: null),
        new(
            RagioneSociale: "CRISTAL GROUP SRL",
            IsPersonaFisica: false,
            PartitaIva: "02717210120",
            CodiceFiscale: "02717210120",
            Indirizzo: "VIA BUONARROTI 7",
            CodicePostale: "21053",
            Localita: "CASTELLANZA",
            Provincia: "VA",
            Paese: "IT",
            Telefono: null,
            Email: null,
            Pec: null,
            Iban: null),
        new(
            RagioneSociale: "Culligan Italy S.r.l",
            IsPersonaFisica: false,
            PartitaIva: "12546450151",
            CodiceFiscale: "12546450151",
            Indirizzo: "Via Ferrarese 156/6",
            CodicePostale: "40128",
            Localita: "Bologna",
            Provincia: "BO",
            Paese: "IT",
            Telefono: null,
            Email: null,
            Pec: null,
            Iban: "IT42T0200805364000030061282"),
        new(
            RagioneSociale: "CVZ ANTINCENDI SRL",
            IsPersonaFisica: false,
            PartitaIva: "02538700127",
            CodiceFiscale: "02538700127",
            Indirizzo: "VIA VOLTERRA N.14",
            CodicePostale: "21052",
            Localita: "BUSTO ARSIZIO",
            Provincia: "VA",
            Paese: "IT",
            Telefono: "0331678220",
            Email: null,
            Pec: null,
            Iban: null),
        new(
            RagioneSociale: "D'INNELLA EUGENIA",
            IsPersonaFisica: true,
            PartitaIva: "10056561219",
            CodiceFiscale: "DNNGNE97L57F839Q",
            Indirizzo: "VIA STAZIO 15",
            CodicePostale: "80123",
            Localita: "NAPOLI",
            Provincia: "NA",
            Paese: "IT",
            Telefono: "081627650",
            Email: null,
            Pec: null,
            Iban: "IT22B0200832974001437196864"),
        new(
            RagioneSociale: "Deutsche Bank S.p.A.",
            IsPersonaFisica: false,
            PartitaIva: "01340740156",
            CodiceFiscale: null,
            Indirizzo: "Piazza del Calendario 3",
            CodicePostale: "20126",
            Localita: "Milano",
            Provincia: "MI",
            Paese: "IT",
            Telefono: null,
            Email: null,
            Pec: null,
            Iban: null),
        new(
            RagioneSociale: "DIELLE di LEZZI DANIELE",
            IsPersonaFisica: false,
            PartitaIva: "02079200966",
            CodiceFiscale: "LZZDNL61B21F205X",
            Indirizzo: "VIA TICINO 11",
            CodicePostale: "20061",
            Localita: "CARUGATE",
            Provincia: "MI",
            Paese: "IT",
            Telefono: "3387977133",
            Email: "dlezzi@libero.it",
            Pec: null,
            Iban: null),
        new(
            RagioneSociale: "DOT Impresa S.r.l.",
            IsPersonaFisica: false,
            PartitaIva: "10927530963",
            CodiceFiscale: "10927530963",
            Indirizzo: "Via Indipendenza 9",
            CodicePostale: "27100",
            Localita: "Pavia",
            Provincia: "PV",
            Paese: "IT",
            Telefono: "0262066373",
            Email: "amm@medicolavoro.org",
            Pec: null,
            Iban: "IT26C0326822300052585592370"),
        new(
            RagioneSociale: "DOTT SSA SERENA PORCARI",
            IsPersonaFisica: false,
            PartitaIva: "04411920756",
            CodiceFiscale: "PRCSRN83B51H793B",
            Indirizzo: "VIA BARI 12/A",
            CodicePostale: "73100",
            Localita: "Lecce",
            Provincia: "LE",
            Paese: "IT",
            Telefono: null,
            Email: null,
            Pec: null,
            Iban: "IT97Z0306234210000001781055"),
        new(
            RagioneSociale: "DR FEDERICO VILLA",
            IsPersonaFisica: false,
            PartitaIva: "04825500160",
            CodiceFiscale: "VLLFRC97C20A794H",
            Indirizzo: "VIA PIAVE N.69",
            CodicePostale: "24033",
            Localita: "CALUSCO D'ADDA",
            Provincia: "BG",
            Paese: "IT",
            Telefono: null,
            Email: null,
            Pec: null,
            Iban: null),
        new(
            RagioneSociale: "DRAGANTI LUCA",
            IsPersonaFisica: true,
            PartitaIva: "03541660126",
            CodiceFiscale: "DRGLCU92A11B300F",
            Indirizzo: "VIA TAGLIAMENTO 4",
            CodicePostale: "21057",
            Localita: "OLGIATE OLONA",
            Provincia: "VA",
            Paese: "IT",
            Telefono: null,
            Email: "luca.draganti@outlook.it",
            Pec: null,
            Iban: "IT07J0503422800000000001661"),
        new(
            RagioneSociale: "ECOLOGIA AMBIENTE SRL A SOCIO UNICO",
            IsPersonaFisica: false,
            PartitaIva: "01890430133",
            CodiceFiscale: "01890430133",
            Indirizzo: "VIA CASATI 12",
            CodicePostale: "22100",
            Localita: "COMO",
            Provincia: "CO",
            Paese: "IT",
            Telefono: null,
            Email: "ecologiaambiente@pec.it",
            Pec: null,
            Iban: null),
        new(
            RagioneSociale: "EDENRED ITALIA Srl",
            IsPersonaFisica: false,
            PartitaIva: "09429840151",
            CodiceFiscale: "01014660417",
            Indirizzo: "VIA PIRELLI 18",
            CodicePostale: "20124",
            Localita: "MILANO",
            Provincia: "MI",
            Paese: "IT",
            Telefono: null,
            Email: null,
            Pec: null,
            Iban: "IT28T0333201600000001112420"),
        new(
            RagioneSociale: "EDIL B. & C. SAS DI BARBIERI STEFANO E C.",
            IsPersonaFisica: false,
            PartitaIva: "03068560121",
            CodiceFiscale: "03068560121",
            Indirizzo: "PIAZZA SANT'ILARIO 108",
            CodicePostale: "21050",
            Localita: "MARNATE",
            Provincia: "VA",
            Paese: "IT",
            Telefono: null,
            Email: null,
            Pec: null,
            Iban: "IT02Q0503450122000000072628"),
        new(
            RagioneSociale: "Farmacia MP S.R.L. a socio unico",
            IsPersonaFisica: false,
            PartitaIva: "11495950963",
            CodiceFiscale: "11495950963",
            Indirizzo: "Via MILANO N,187",
            CodicePostale: "20832",
            Localita: "DESIO",
            Provincia: "MI",
            Paese: "IT",
            Telefono: "0362303840",
            Email: null,
            Pec: null,
            Iban: null),
        new(
            RagioneSociale: "Fastweb S.p.A.",
            IsPersonaFisica: false,
            PartitaIva: "12878470157",
            CodiceFiscale: "12878470157",
            Indirizzo: "Piazza Adriano Olivetti 1",
            CodicePostale: "20139",
            Localita: "Milano",
            Provincia: "MI",
            Paese: "IT",
            Telefono: null,
            Email: null,
            Pec: null,
            Iban: null),
        new(
            RagioneSociale: "FBM HEALTHCARE S.R.L.- In Liquidazione",
            IsPersonaFisica: false,
            PartitaIva: "07791381002",
            CodiceFiscale: "07791381002",
            Indirizzo: "VIA MELOZZO DA FORLI' 35",
            CodicePostale: "20076",
            Localita: "MEDIGLIA",
            Provincia: "MI",
            Paese: "IT",
            Telefono: "0652440372",
            Email: "fbm.amministrazione@fbmhealth.it",
            Pec: null,
            Iban: "IT68K0608501600000000024604"),
        new(
            RagioneSociale: "FORMENTI PAOLO JACOPO",
            IsPersonaFisica: true,
            PartitaIva: "07632760968",
            CodiceFiscale: "FRMPJC77A26I625K",
            Indirizzo: "VIALE DEI GIARDINI 9",
            CodicePostale: "20831",
            Localita: "SEREGNO",
            Provincia: "MB",
            Paese: "IT",
            Telefono: null,
            Email: null,
            Pec: null,
            Iban: "IT50W0569633840000002922X85"),
        new(
            RagioneSociale: "FRIGNATI LUCA MARIA VITTORIO",
            IsPersonaFisica: true,
            PartitaIva: "02808770164",
            CodiceFiscale: "FRGLMR67R15F205C",
            Indirizzo: "VIA PIETRO MASCAGNI N 6 6",
            CodicePostale: "20865",
            Localita: "USMATE VELATE",
            Provincia: "MB",
            Paese: "IT",
            Telefono: null,
            Email: null,
            Pec: null,
            Iban: null),
        new(
            RagioneSociale: "HENRY SCHEIN KRUGG S.R.L",
            IsPersonaFisica: false,
            PartitaIva: "13088630150",
            CodiceFiscale: null,
            Indirizzo: "VIA GRAN SAN BERNARDO, STRADA 7, PALAZZO R/1",
            CodicePostale: "20089",
            Localita: null,
            Provincia: null,
            Paese: "IT",
            Telefono: null,
            Email: null,
            Pec: null,
            Iban: "IT29J0200805364000030068362"),
        new(
            RagioneSociale: "HORSE ACADEMY MILANO SSD A",
            IsPersonaFisica: false,
            PartitaIva: "03970630129",
            CodiceFiscale: "03970630129",
            Indirizzo: "VIA BALZARINE SNC",
            CodicePostale: "21054",
            Localita: "FAGNANO OLONA",
            Provincia: "VA",
            Paese: "IT",
            Telefono: null,
            Email: null,
            Pec: null,
            Iban: null),
        new(
            RagioneSociale: "IGLESIAS BUSCA MARIA DEL PILAR",
            IsPersonaFisica: false,
            PartitaIva: "12163850964",
            CodiceFiscale: "GLSMDL59L71Z131Z",
            Indirizzo: "VIA MACHIAVELLI 3",
            CodicePostale: "20037",
            Localita: "Paderno Dugnano",
            Provincia: "MI",
            Paese: "IT",
            Telefono: "3386320438",
            Email: "pilar03ig@yahoo.it",
            Pec: null,
            Iban: "IT68I0503433522000000003711"),
        new(
            RagioneSociale: "Infinity srl",
            IsPersonaFisica: false,
            PartitaIva: "04052950161",
            CodiceFiscale: "04052950161",
            Indirizzo: "Via Azzano San Paolo 14",
            CodicePostale: "24040",
            Localita: "Stezzano",
            Provincia: "BG",
            Paese: "IT",
            Telefono: null,
            Email: null,
            Pec: null,
            Iban: "IT86Z0894053570000000001099"),
        new(
            RagioneSociale: "Invisalign S.r.l.",
            IsPersonaFisica: false,
            PartitaIva: "03301470963",
            CodiceFiscale: null,
            Indirizzo: "Via Milano, 10",
            CodicePostale: "20097",
            Localita: "San Donato Milanese",
            Provincia: "MI",
            Paese: "IT",
            Telefono: null,
            Email: null,
            Pec: null,
            Iban: "IT45X0338001600000014427029"),
        new(
            RagioneSociale: "ITES COM S.R.L.",
            IsPersonaFisica: false,
            PartitaIva: "03390080129",
            CodiceFiscale: "03390080129",
            Indirizzo: "Via Ercole Ferrario 19",
            CodicePostale: "21013",
            Localita: "Gallarate",
            Provincia: "VA",
            Paese: "IT",
            Telefono: "0331775555",
            Email: "ITESCOM@ITESCOM.IT",
            Pec: null,
            Iban: null),
        new(
            RagioneSociale: "J Dental Care Srl",
            IsPersonaFisica: false,
            PartitaIva: "03071260362",
            CodiceFiscale: "03071260362",
            Indirizzo: "VIA DINO CAMPANA 2",
            CodicePostale: "41123",
            Localita: "MODENA",
            Provincia: "MO",
            Paese: "IT",
            Telefono: null,
            Email: null,
            Pec: null,
            Iban: null),
        new(
            RagioneSociale: "KAMH AHMED ABDELAZIZ AHME",
            IsPersonaFisica: false,
            PartitaIva: "04692290986",
            CodiceFiscale: "KMHHDB00A11Z336V",
            Indirizzo: "VIA TERNI",
            CodicePostale: "25085",
            Localita: "Gavardo",
            Provincia: "BS",
            Paese: "IT",
            Telefono: null,
            Email: "ahmed.kamh125@gmail.com",
            Pec: null,
            Iban: null),
        new(
            RagioneSociale: "LABORATORIO ODONTOTECNICO M.B. SRL",
            IsPersonaFisica: false,
            PartitaIva: "02381920137",
            CodiceFiscale: null,
            Indirizzo: "VIA CARDUCCI, 10",
            CodicePostale: "22070",
            Localita: "MONTANO LUCINO",
            Provincia: "CO",
            Paese: "IT",
            Telefono: null,
            Email: null,
            Pec: null,
            Iban: null),
        new(
            RagioneSociale: "LAZZARI GIUSEPPE",
            IsPersonaFisica: true,
            PartitaIva: "02696590138",
            CodiceFiscale: "LZZGPP59D23L682X",
            Indirizzo: "VIA DEGLI OLEANDRI 20",
            CodicePostale: "17019",
            Localita: "VARAZZE",
            Provincia: "SV",
            Paese: "IT",
            Telefono: null,
            Email: "gi.lazzari1959@gmail.com",
            Pec: null,
            Iban: "IT39M0306933362100000009198"),
        new(
            RagioneSociale: "LYRECO ITALIA SRL",
            IsPersonaFisica: false,
            PartitaIva: "11582010150",
            CodiceFiscale: null,
            Indirizzo: "Via Giovanni Mayr, 10",
            CodicePostale: "20122",
            Localita: null,
            Provincia: null,
            Paese: "IT",
            Telefono: null,
            Email: null,
            Pec: null,
            Iban: "IT60L0200850240000106413548"),
        new(
            RagioneSociale: "MARCI' RACHELE",
            IsPersonaFisica: true,
            PartitaIva: "02106470160",
            CodiceFiscale: "MRCRHL60B53G273H",
            Indirizzo: "VIA GIULIO CESARE 50",
            CodicePostale: "24123",
            Localita: "Bergamo",
            Provincia: "BG",
            Paese: "IT",
            Telefono: null,
            Email: "RACHELEMAR@GMAIL.COM",
            Pec: null,
            Iban: null),
        new(
            RagioneSociale: "Mark Srl",
            IsPersonaFisica: false,
            PartitaIva: "02099150126",
            CodiceFiscale: "02099150126",
            Indirizzo: "VIA T. TASSO, 43",
            CodicePostale: "21052",
            Localita: "BUSTO ARSIZIO",
            Provincia: "VA",
            Paese: "IT",
            Telefono: "0331323255",
            Email: "gianni.marksrl@gmail.com",
            Pec: null,
            Iban: null),
        new(
            RagioneSociale: "MOI DENTAL S.R.L.",
            IsPersonaFisica: false,
            PartitaIva: "11297420967",
            CodiceFiscale: "11297420967",
            Indirizzo: "Viale Monte Ceneri 78",
            CodicePostale: "20155",
            Localita: "Milano",
            Provincia: "MI",
            Paese: "IT",
            Telefono: null,
            Email: null,
            Pec: null,
            Iban: null),
        new(
            RagioneSociale: "Mouzhan Maghsoudlou Rad",
            IsPersonaFisica: false,
            PartitaIva: "14499670967",
            CodiceFiscale: "MGHMHN95L50Z224E",
            Indirizzo: "Viale Cesare Battisti,8B",
            CodicePostale: "20854",
            Localita: "VEDANO AL LAMBRO",
            Provincia: "MB",
            Paese: "IT",
            Telefono: null,
            Email: "moozhan_7366@yahoo.com",
            Pec: null,
            Iban: "IT55Q0366901600589884667018"),
        new(
            RagioneSociale: "ODONTOCAP S.R.L.",
            IsPersonaFisica: false,
            PartitaIva: "07033140968",
            CodiceFiscale: null,
            Indirizzo: "VIA ALESSANDRINA 45/a",
            CodicePostale: "20095",
            Localita: "CUSANO MILANINO",
            Provincia: "MI",
            Paese: "IT",
            Telefono: null,
            Email: null,
            Pec: null,
            Iban: null),
        new(
            RagioneSociale: "Panizza dr Sergio Odontoiatra",
            IsPersonaFisica: false,
            PartitaIva: "04773630969",
            CodiceFiscale: "PNZSRG74M08F205W",
            Indirizzo: "via Victor Hugo 2",
            CodicePostale: "20017",
            Localita: "Rho",
            Provincia: "MI",
            Paese: "IT",
            Telefono: null,
            Email: "sergiopaniz@libero.it",
            Pec: null,
            Iban: null),
        new(
            RagioneSociale: "PROVENZANO DANIELE",
            IsPersonaFisica: true,
            PartitaIva: "04034370165",
            CodiceFiscale: "PRVDNL88D28G273O",
            Indirizzo: "VIALE GIULIO CESARE 50",
            CodicePostale: "24122",
            Localita: "BERGAMO",
            Provincia: "BG",
            Paese: "IT",
            Telefono: null,
            Email: null,
            Pec: null,
            Iban: "IT15F0503411103000000000781"),
        new(
            RagioneSociale: "RDR Dental s.a.s. di Babolin Danilo e Vanzulli",
            IsPersonaFisica: false,
            PartitaIva: "02048530121",
            CodiceFiscale: null,
            Indirizzo: "via Puricelli, 3",
            CodicePostale: "21013",
            Localita: "Gallarate",
            Provincia: "VA",
            Paese: "IT",
            Telefono: null,
            Email: null,
            Pec: null,
            Iban: null),
        new(
            RagioneSociale: "SAPIA PRATESI & PARTNERS S.R.L.",
            IsPersonaFisica: false,
            PartitaIva: "01801930494",
            CodiceFiscale: "01801930494",
            Indirizzo: "VIA NEDO NADI 1",
            CodicePostale: "57123",
            Localita: "LIVORNO",
            Provincia: "LI",
            Paese: "IT",
            Telefono: "05861945560",
            Email: "sapiapratesisrl@legalmail.it",
            Pec: null,
            Iban: null),
        new(
            RagioneSociale: "SAPIO LIFE S.r.l.",
            IsPersonaFisica: false,
            PartitaIva: "02006400960",
            CodiceFiscale: "02006400960",
            Indirizzo: "Via S. Pellico, 48",
            CodicePostale: "20900",
            Localita: "Monza",
            Provincia: "MB",
            Paese: "IT",
            Telefono: "800014341",
            Email: "fatturazione.clienti@sapio.it",
            Pec: null,
            Iban: null),
        new(
            RagioneSociale: "Sorgenia S.p.A",
            IsPersonaFisica: false,
            PartitaIva: "12874490159",
            CodiceFiscale: "07756640012",
            Indirizzo: "Via Alessandro Algardi 4",
            CodicePostale: "20148",
            Localita: "MILANO",
            Provincia: "MI",
            Paese: "IT",
            Telefono: null,
            Email: null,
            Pec: null,
            Iban: null),
        new(
            RagioneSociale: "SWEDEN & MARTINA S.p.A.",
            IsPersonaFisica: false,
            PartitaIva: "00401550280",
            CodiceFiscale: "00401550280",
            Indirizzo: "VIA VENETO, 10",
            CodicePostale: "35020",
            Localita: "DUE CARRARE",
            Provincia: "PD",
            Paese: "IT",
            Telefono: "049/9124300",
            Email: "info@sweden-martina.com",
            Pec: null,
            Iban: "IT61Q0898262680030000500272"),
        new(
            RagioneSociale: "TIBICHI EDWIN FLAVIUS",
            IsPersonaFisica: true,
            PartitaIva: "04208120131",
            CodiceFiscale: "TBCDNF00P27Z129P",
            Indirizzo: "VIA FIUME 3",
            CodicePostale: "22044",
            Localita: "INVERIGO",
            Provincia: "CO",
            Paese: "IT",
            Telefono: null,
            Email: "etibichi@yahoo.com",
            Pec: null,
            Iban: "IT11X0200809500000430288497"),
        new(
            RagioneSociale: "Triulzi Margherita",
            IsPersonaFisica: false,
            PartitaIva: "11468820961",
            CodiceFiscale: "TRLMGH93C66I577I",
            Indirizzo: "Via San Pio V, 5",
            CodicePostale: "20123",
            Localita: "Milano",
            Provincia: "MI",
            Paese: "IT",
            Telefono: null,
            Email: "triulzi.margherita@gmail.com",
            Pec: null,
            Iban: "IT44K0306901791100000001564"),
        new(
            RagioneSociale: "VIGILANZA DESIO-ALL' ERTA SRL",
            IsPersonaFisica: false,
            PartitaIva: "02916480961",
            CodiceFiscale: "01323070126",
            Indirizzo: "VIA LIGURIA 4",
            CodicePostale: "20025",
            Localita: "LEGNANO",
            Provincia: "MI",
            Paese: "IT",
            Telefono: null,
            Email: null,
            Pec: null,
            Iban: "IT60L0200850240000106413548"),
        new(
            RagioneSociale: "WISIL LAB MILANO SRL",
            IsPersonaFisica: false,
            PartitaIva: "14271140965",
            CodiceFiscale: "14271140965",
            Indirizzo: "Viale Abruzzi 34",
            CodicePostale: "20131",
            Localita: "MILANO",
            Provincia: "MI",
            Paese: "IT",
            Telefono: "0229404192",
            Email: null,
            Pec: null,
            Iban: null),
    };
}
